### ISSUE TITLE
Ability to choose measure when entering or editing value

### ISSUE THREAD

**Issue by underlow** [InfoWings/Knowledge-Net#263]
When entering/editing/viewing objects, it is required to provide consistency with requirements "Editing/Entering property values" which are concerned with value "measures"

Quote from requirements:
- Value measures and corresponding aspect measures must belong to the same measure group, whereas if value measure is different from corresponding aspect measure, the reference to value measure should be stored along with value.
- User should be able to change value measure when entering the value from the list of measures that belong to the same group as corresponding aspect measures. Wherein the displayed value should be recalculated according to conversion rules.
- By default the corresponding aspect measure should be used

**Comment by kochkr** [comment]
Discussions regarding current state of the ticket led to the next changes:
* User MUST always select the measure unit for the value. Value without selected measure unit should be considered illegal. The presence of `measureName` in any value changing request should be validated. Measure in corresponding aspect should serve as default for user-selected measure, but any changes to that measure should not be reflected on any existing values. Those changes should affect only new values, created after the changes.
* According to the previous point, all the values that are not linked with measures should be considered illegal. So it is required to add to all existing values a link to the measure, that is specified currently in corresponding aspect. The implementation may be database script or any other way that would make all existing values legal from new point of view.

For further discussion there is left one subject:
* It is required to add a field "User-entered data" to the value entity in order to eliminate situations where conversion to base type and back leads to a bit skewed value. Right now this effect can be observed on the "Temperature" measure group, when entering value in Fahrenheits.
