### ISSUE TITLE
It is possible to create objects with same names and subjects

### ISSUE THREAD

**Issue by tushkanova** [InfoWings/Knowledge-Net#274]
Currently it can be observed on `catalog.reflexia.com`

**Comment by tushkanova** [comment]
Perhaps this is the server side problem.
Failed to reproduce it on frontend.

**Comment by kochkr** [comment]
![screenshot from 2018-08-23 15-41-43](https://user-images.githubusercontent.com/8794225/44525897-1b478f00-a6eb-11e8-9701-82840d08ab53.png)

**Comment by kochkr** [comment]
So the thing is: all validation rules are triggered as expected. The problem on catalog is that there is a difference between these two objects: one of them has two spaces between "Object" and "7", and another one has one space between the same words. That is why this situation is valid.
There is another concern, though. The problem is the rendering of the name attribute of any entity, because it is just put into the html tag as content.
