### ISSUE TITLE
Fix GIUD copy icon

### ISSUE THREAD

**Issue by tushkanova** [InfoWings/Knowledge-Net#364]
After several reload of any KN page GIUD copy icon disappears. Strange rectangle is shown instead. In order to see GIUD copy icon again one should open KN in new window.

**Comment by sreznick** [comment]
I'm not completely sure that I really fixed it because it is not so easy to reproduce for me.
However I've made investigations and figured out that these icons were implemented as so called
"icon fonts" - it is css feature where requested icon is specified in declarative way as numeric code and it is browser
responsibility to find approprate image.
These icons are stored together with ordinary fonts.
And it is quite possible that browser can find only some font files where such icons are not defined.
(In general it happens that not all code points are supported by font file).

And my fix is to use SVG images distributed together with application.

I hope this will help.
